services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: casino_db
      POSTGRES_USER: casino_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
