# Generated by Django 5.2.7 on 2025-10-09 03:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaderboard",
            options={"ordering": ["-score"],
                    "verbose_name_plural": "Leaderboards"},
        ),
        migrations.RemoveField(
            model_name="leaderboard",
            name="username",
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(
                null=True, blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="score",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.UniqueConstraint(
                fields=("user", "game_name", "score", "date_played"),
                name="uniq_entry_snapshot",
            ),
        ),
    ]
