# Generated by Django 5.2.7 on 2025-10-10 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("max_score", models.PositiveIntegerField(default=0)),
                ("rules", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="leaderboard",
            options={"ordering": ["-score"], "verbose_name_plural": "Leaderboards"},
        ),
        migrations.RenameField(
            model_name="leaderboard",
            old_name="date_played",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="leaderboard",
            name="game_name",
        ),
        migrations.RemoveField(
            model_name="leaderboard",
            name="username",
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="users.userprofile",
            ),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="score",
            field=models.PositiveIntegerField(),
        ),
        migrations.AddField(
            model_name="leaderboard",
            name="game",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scores",
                to="games.game",
            ),
        ),
        migrations.AddConstraint(
            model_name="leaderboard",
            constraint=models.UniqueConstraint(
                fields=("user", "game", "score", "created_at"),
                name="uniq_entry_snapshot",
            ),
        ),
    ]
