# Generated by Django 5.2.7 on 2025-10-09 03:20
# pylint: disable=unused-argument, unused-variable

"""This module holds the migration to backfill null users in Leaderboard entries"""
from django.db import migrations

def backfill_users(apps, schema_editor):
    # Import models through the historical apps registry
    User = apps.get_model('auth', 'User')
    Leaderboard = apps.get_model('games', 'Leaderboard')

    # Get or create a fallback "system" user
    system_user, created = User.objects.get_or_create(username='system', defaults={'password': 'temporary123'})

    # Update all Leaderboard rows missing a user
    updated_count = Leaderboard.objects.filter(user__isnull=True).update(user=system_user)
    print(f"Backfilled {updated_count} leaderboard entries with system user.")

class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_leaderboard_options_and_more'),  # adjust this to match your last migration name
    ]

    operations = [
        migrations.RunPython(backfill_users),
    ]
